export const INITIALSTATE = {
  prisonUnit: "",
  relevantContent: "",
  question1: {
    index: -1,
    value: "",
    question1: { index: 1, value: "" },
    question2: { index: 2, value: "" },
    question3: { index: 3, value: "" },
    question4: { index: 4, value: "" },
    question5: { index: 5, value: "" },
    question6: { index: 6, value: "" },
    question7: { index: 7, value: "" },
    question8: { index: 8, value: "" },
    question9: { index: 9, value: "" },
    question10: { index: 10, value: "" },
  },
  question2: "",
  question3: "",
  question4: "",
  question6: "",
  question5: "",
  question7: "",
  question8: "",
  question9: "",
  question10: "",
  perception: "",
};
