export const CheckBoxType = [
  "não tem história descrita",
  "Vida de Prem Rawat (Introd.)",
  "Rei Filipe II e Esparta (Cap 1)",
  "A Rainha e o colar (Cap 1)",
  "Aladim e sua lâmpada mágica (Cap 2)",
  "O Vendedor e pedra (Cap 2)",
  "25550 Dias (Cap 2)",
  "A Vida entre duas paredes (Cap 2)",
  "O Médico que tentou enganar a morte (Cap 2)",
  "Os 3 pedidos do Rei Alexandre (Cap 2)",
  "Citações e poemas (Cap 3)",
  "Mais importante: Sol ou Lua (Cap 4)",
  "Átomo Indivisível (Cap 4)",
  "O jovem, o sábio e o balde furado (Cap 4)",
  "O cético que queria contestar Shiri Hans Ji Maharaj (Cap 4)",
  "Akbar, sua esposa e Birbal (Cap 4)",
  "O homem velho e o fardo de madeira (Cap 5)",
  "O marido, a mulher e o cavalo (Cap 5)",
  "O que as pessoas vão pensar de mim (Cap 5)",
  "A tigela de Buda (Cap 5)",
  "Sem resmungar (Cap 5)",
  "O ladrão que não encontrou o dinheiro (Cap 5)",
  "O zero e o um (Cap 5)",
  "A vida é dirigir um carro (Cap 5)",
  "Quem é o idiota - Akbar e Birbal? (Cap 5)",
  "Desembrulhando o presente (Cap 6)",
  "Rei, Ministro, Cavaleiro e Tribo Canibal (Cap 6)",
  "Nuvem mais escura (Cap 6)",
  "Motorista com música alta (Cap 6)",
  "Peixe com sede (Cap 6)",
  "Quebrador de pedras (Cap 6)",
  "Tudo Dói (Cap 7)",
  "A morte do pai de Prem Rawat (Cap 7)",
  "O fazendeiro, o burro e a vaca (Cap 7)",
  "O piloto e o avião (Cap 7)",
  "Krishna e o Guerreiro Arjun (Cap 8)",
  "Fuga pelo Muro (Cap 8)",
  "A Vingança (Cap 8)",
  "Competição entre o Vento e o Sol (Cap 8)",
  "O Rei e o Rouxinol (Cap 9)",
  "O dedo no carro do filho de Prem Rawat (Cap 9)",
  "O homem que caiu da cordilheira (Cap 10)",
  "Moedas para Deus (Cap 10)",
  "O homem numa perna só (Cap 10)",
  "Quem é maior que Deus? (Cap 10)",
  "O Espelho (Cap 10)",
  "Os dois monges cruzando o rio (Cap 10)",
  "A Bicicleta (Cap 10)",
  "O Paraíso e o Inferno (Cap 10)",
  "O homem que pensava ser um grão de trigo (Cap 11)",
  "O homem com sede e a gravata (Cap 11)",
  "O Tijolo (Cap 11)",
  "O Relógio (Cap 11)",
  "Uma gota do oceano (Cap 11)",
  "A vida como um livro (Cap 11)",
  "Conhecimento e o Mestre (Cap 11)",
  "Aprendendo a esquiar (Cap 11)",
  "Prem Rawat pode flutuar (Cap 11)",
  "Férias de ser poeira (Cap 11)",
  "Carpe Diem (Cap 11)",
  "Lobo bom, lobo mau (Cap 11)",
  "O pássaro e a gaiola (Cap 11)",
  "Outra (descrever no próximo item)",
];
