/* eslint-disable max-len */

const Links = [
  {
    id: 1,
    img: "static/images/downloads/paz.png",
    title: "Paz é ... Paz",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz...",
    href: "arquivosDownload/pazE01.pdf",
  },
  {
    id: 2,
    img: "static/images/downloads/arqueiro.png",
    title: "O Arqueiro e o Mercador",
    body: "Era uma vez um exímio arqueiro que conseguia disparar uma flecha, atingir o alvo e disparar em seguida outra flecha....",
    href: "arquivosDownload/oArqueiroEOMercador02.pdf",
  },
  {
    id: 3,
    img: "static/images/downloads/coelho.png",
    title: "O Coelho e o Leão",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz...",
    href: "arquivosDownload/oCoelhoEOLeao03.pdf",
  },
  {
    id: 4,
    img: "static/images/downloads/espelho.png",
    title: "O Espelho Na Parede",
    body: "Era uma vez uma aldeia distante onde viviam pessoas muito simples. Um dia, chegou um turista. Na manhã seguinte, ele pegou seu espelho e colocou-o na parede para se barbear..",
    href: "arquivosDownload/oEspelhoNaParede04.pdf",
  },
  {
    id: 5,
    img: "static/images/downloads/arvore.png",
    title: "O Jardim da Vida",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/oJardimDaVida05.pdf",
  },
  {
    id: 6,
    img: "static/images/downloads/leao.png",
    title: "O Leão e a Ovelha",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/oLeaoEAOvelha06.pdf",
  },
  {
    id: 7,
    img: "static/images/downloads/paz.png",
    title: "O Som de Estar Contente",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/oSomDeEstarContente07.pdf",
  },
  {
    id: 8,
    img: "static/images/downloads/irmaos.png",
    title: "Os Três Irmãos",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/osTresIrmaos08.pdf",
  },
  {
    id: 9,
    img: "static/images/downloads/formiga.png",
    title: "A História da Formiga",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/aHistoriaDaFormiga09.pdf",
  },
  {
    id: 10,
    img: "static/images/downloads/caderno.png",
    title: "A Melhor Hora",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/aMelhorHora10.pdf",
  },
  {
    id: 11,
    img: "static/images/downloads/jornada.png",
    title: "Ansiando Pela Paz",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/ansiandoPelaPaz11.pdf",
  },
  {
    id: 12,
    img: "static/images/downloads/pedra.png",
    title: "Quando Você Tem Clareza",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/quandoVoceTemClareza12.pdf",
  },
  {
    id: 13,
    img: "static/images/downloads/porta.png",
    title: "Sabe Quem Você É?",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/sabeQuemVoceE13.pdf",
  },
  {
    id: 14,
    img: "static/images/downloads/paz.png",
    title: "Sua Escolha",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz.",
    href: "arquivosDownload/suaEscolha14.pdf",
  },
  {
    id: 15,
    img: "static/images/downloads/paz.png",
    title: "Um Mundo de Entendimento",
    body: "A vida é um presente. Eu quero entender isso com a maior clareza possível antes que eu perca a capacidade de entender.",
    href: "arquivosDownload/umMundoDeEntendimento15.pdf",
  },
];

export default Links;
