/* eslint-disable max-len */

const Links = [
  {
    id: 1,
    img: "static/images/downloads/paz.png",
    title: "Paz é ... Paz",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz...",
    href: "arquivosDownload/pazE01.pdf",
  },
  {
    id: 2,
    img: "static/images/downloads/arqueiro.png",
    title: "O Arqueiro e o Mercador",
    body: "Era uma vez um exímio arqueiro que conseguia disparar uma flecha, atingir o alvo e disparar em seguida outra flecha...",
    href: "arquivosDownload/oArqueiroEOMercador02.pdf",
  },
  {
    id: 3,
    img: "static/images/downloads/coelho.png",
    title: "O Coelho e o Leão",
    body: "Queremos ser felizes. Ninguém nos disse isso. Nossas mães não nos disseram. “Sabe de uma coisa? Você vai querer ser feliz...",
    href: "arquivosDownload/oCoelhoEOLeao03.pdf",
  },
  {
    id: 4,
    img: "static/images/downloads/espelho.png",
    title: "O Espelho Na Parede",
    body: "Era uma vez uma aldeia distante onde viviam pessoas muito simples. Um dia, chegou um turista. Na manhã seguinte, ele pegou seu espelho e colocou-o na parede para se barbear...",
    href: "arquivosDownload/oEspelhoNaParede04.pdf",
  },
  {
    id: 5,
    img: "static/images/downloads/arvore.png",
    title: "O Jardim da Vida",
    body: "É uma metáfora, mas é verdade. Quando chegamos a este mundo, algumas sementes nos são dadas, e as perguntas são: O que faremos com essas sementes?",
    href: "arquivosDownload/oJardimDaVida05.pdf",
  },
  {
    id: 6,
    img: "static/images/downloads/leao.png",
    title: "O Leão e a Ovelha",
    body: "Às vezes esquecemos quem somos. por Prem Rawat Ficamos tão envolvidos em nossas causas e definições que não vemos que cada ser humano tem a mesma ambição: ser feliz, estar em paz...",
    href: "arquivosDownload/oLeaoEAOvelha06.pdf",
  },
  {
    id: 7,
    img: "static/images/downloads/paz.png",
    title: "O Som de Estar Contente",
    body: "Todos nós somos seres humanos. E de certa forma nossas vidas são semelhantes. Acordamos de manhã. Temos nossos trabalhos, nossas responsabilidades...",
    href: "arquivosDownload/oSomDeEstarContente07.pdf",
  },
  {
    id: 8,
    img: "static/images/downloads/irmaos.png",
    title: "Os Três Irmãos",
    body: "Era uma vez três irmãos que tinham vivido uma infância abastada. Quando ficaram mais velhos, seus pais morreram e eles perderam todo o dinheiro...",
    href: "arquivosDownload/osTresIrmaos08.pdf",
  },
  {
    id: 9,
    img: "static/images/downloads/formiga.png",
    title: "A História da Formiga",
    body: "Tendemos a analizar tudo. Mas quando sinto sede, não quero uma análise da água. Não quero descrições da água. Só quero saber de conseguir água para saciar minha sede. Essa é a questão, saciar a sede...",
    href: "arquivosDownload/aHistoriaDaFormiga09.pdf",
  },
  {
    id: 10,
    img: "static/images/downloads/caderno.png",
    title: "A Melhor Hora",
    body: "Quando vim para o Ocidente, eu tinha apenas 13 anos. E as pessoas vinham me ver, adultos mais velhos, mais educados, mais inteligentes do que eu. Pelo menos, era assim que eles pareciam...",
    href: "arquivosDownload/aMelhorHora10.pdf",
  },
  {
    id: 11,
    img: "static/images/downloads/jornada.png",
    title: "Ansiando Pela Paz",
    body: "Eu estou aqui para falar sobre algo muito fundamental. Você tem um anseio, um desejo a ser preenchido. E esse desejo não desaparecerá enquanto você viver...",
    href: "arquivosDownload/ansiandoPelaPaz11.pdf",
  },
  {
    id: 12,
    img: "static/images/downloads/pedra.png",
    title: "Quando Você Tem Clareza",
    body: "Você me ouvirá dizer esta palavra muitas, muitas vezes: clareza.O que quero dizer com ela? O que é clareza? Ter clareza é estar claro, saber o valor do hoje...",
    href: "arquivosDownload/quandoVoceTemClareza12.pdf",
  },
  {
    id: 13,
    img: "static/images/downloads/porta.png",
    title: "Sabe Quem Você É?",
    body: "Você sabe quem você é? Você não tem que responder isso para os outros. Não para a sua esposa ou seu marido, e não para seus filhos...",
    href: "arquivosDownload/sabeQuemVoceE13.pdf",
  },
  {
    id: 14,
    img: "static/images/downloads/paz.png",
    title: "Sua Escolha",
    body: "Paz é quando você está inteiro. Paz é quando você está completo, quando você entende. Tudo depende das escolhas que você faz em sua vida...",
    href: "arquivosDownload/suaEscolha14.pdf",
  },
  {
    id: 15,
    img: "static/images/downloads/paz.png",
    title: "Um Mundo de Entendimento",
    body: "A vida é um presente. Eu quero entender isso com a maior clareza possível antes que eu perca a capacidade de entender...",
    href: "arquivosDownload/umMundoDeEntendimento15.pdf",
  },
];

export default Links;
