/* eslint-disable max-lines */
/* eslint-disable max-len */

const Links = [
  {
    id: 1,
    img: "static/images/downloads/paz.png",
    title: "Tema 1 - Paz é...",
    body: "Toda a gente ouviu dizer imensas vezes a palavra paz. Mas de que paz estamos a falar? Há muito tempo que falo sobre paz e tenho reparado que cada pessoa tem a sua própria definição de paz.",
    href: "arquivosDownload/v2/tema 1 - paz.pdf",
  },
  {
    id: 2,
    img: "static/images/downloads/pedra.png",
    title: "Tema 2 - O Home de Negócios e a Pedra Mágica",
    body: "HAVIA UM HOMEM DE NEGÓCIOS que tinha um pequeno comércio. Claro que, sendo um homem de negócios, o seu desejo era obter o maior lucro possível.",
    href: "arquivosDownload/v2/Tema 2 - Apreciacao.pdf",
  },
  {
    id: 3,
    img: "static/images/downloads/paz.png",
    title: "Tema 3 - Força interior",
    body: "Uma  pessoa  pode  ser  incrivelmente  bem  sucedida  e,  ao  mesmo  tempo,  incrivelmente triste, porque a verdadeira felicidade manifesta-se de dentro para fora.",
    href: "arquivosDownload/v2/tema 3 - forca interior.pdf",
  },
  {
    id: 4,
    img: "static/images/downloads/leao.png",
    title: "Tema 4 - o Leão e as Ovelhas",
    body: "Por vezes, esquecemo-nos de quem somos. Deixamo-nos envolver tanto nas nossas causas, nas nossas definições, que não vemos que cada ser humano em a mesma ambição: ser feliz, estar em paz.",
    href: "arquivosDownload/v2/Tema 4 - Auto Conhecimento.pdf",
  },
  {
    id: 5,
    img: "static/images/downloads/formiga.png",
    title: "Tema 5 - A História da Formiga",
    body: "Tendemos a analisar tudo. Mas quando eu tenho sede, não quero uma análise da água. Não quero descrições da água. Só quero saber como arranjar água para poder saciar a minha sede. É disso que se trata, de saciar a sede.",
    href: "arquivosDownload/v2/tema 5 - clareza.pdf",
  },
  {
    id: 6,
    img: "static/images/downloads/arqueiro.png",
    title: "Tema 6 - O Arqueiro e o Vendedor de Azeite",
    body: "HAVIA UM HOMEM que era um arqueiro muito bom. Conseguia disparar uma flecha, acertar no alvo e, depois, com outra flecha, rachar a primeira. Costumava andar de aldeia em aldeia a mostrar as suas habilidades.",
    href: "arquivosDownload/v2/Tema 6 - Compreensao.pdf",
  },
  {
    id: 7,
    img: "static/images/downloads/paz.png",
    title: "Tema 7 - Dignidade",
    body: "Quando penso naquilo que quero, simplesmente como ser humano, a lista de pedidos não é muito longa. O que quero, e o que todas as pessoas querem, é a oportunidade de crescer. A oportunidade de ser feliz.",
    href: "arquivosDownload/v2/tema 7 - dignidade.pdf",
  },
  {
    id: 8,
    img: "static/images/downloads/paz.png",
    title: "Tema 8 - Capacidade de Escolha",
    body: "Paz é quando te sentes inteiro. Paz é quando te sentes completo, quando compreendes. Tudo depende das escolhas que fazes na vida.",
    href: "arquivosDownload/v2/tema 8 - capacidade de escolha.pdf",
  },
  {
    id: 9,
    img: "static/images/downloads/paz.png",
    title: "Tema 9 - Esperança",
    body: "Eu tenho uma coisa especial para te dizer: há esperança, todos os dias. Não é uma questão de meses nem é uma questão de semanas. Não se trata de ontem ou amanhã.",
    href: "arquivosDownload/v2/tema 9 - esperanca.pdf",
  },
  {
    id: 10,
    img: "static/images/downloads/paz.png",
    title: "Tema 10 - Contentamento",
    body: "Somos todos seres humanos. E de certa forma, as nossas vidas são muito semelhantes. Acordamos de manhã. Temos nossos empregos, as nossas responsabilidades. Às vezes, as coisas correm-nos de feição, outras vezes não.",
    href: "arquivosDownload/v2/tema 10 - contentamento.pdf",
  },
  {
    id: 11,
    img: "static/images/downloads/paz.png",
    title: "Paz é ... Paz",
    body: "Você já ouviu a palavra paz muitas vezes. No entanto, de que tipo de paz estamos falando? Por todo este tempo que falo da paz, tenho notado que cada pessoa tem sua própria definição do que é a paz...",
    href: "arquivosDownload/pazE01.pdf",
  },
  {
    id: 12,
    img: "static/images/downloads/arqueiro.png",
    title: "O Arqueiro e o Mercador",
    body: "Era uma vez um exímio arqueiro que conseguia disparar uma flecha, atingir o alvo e disparar em seguida outra flecha...",
    href: "arquivosDownload/oArqueiroEOMercador02.pdf",
  },
  {
    id: 13,
    img: "static/images/downloads/coelho.png",
    title: "O Coelho e o Leão",
    body: "Queremos ser felizes. Ninguém nos disse isso. Nossas mães não nos disseram. “Sabe de uma coisa? Você vai querer ser feliz...",
    href: "arquivosDownload/oCoelhoEOLeao03.pdf",
  },
  {
    id: 14,
    img: "static/images/downloads/espelho.png",
    title: "O Espelho Na Parede",
    body: "Era uma vez uma aldeia distante onde viviam pessoas muito simples. Um dia, chegou um turista. Na manhã seguinte, ele pegou seu espelho e colocou-o na parede para se barbear...",
    href: "arquivosDownload/oEspelhoNaParede04.pdf",
  },
  {
    id: 15,
    img: "static/images/downloads/arvore.png",
    title: "O Jardim da Vida",
    body: "É uma metáfora, mas é verdade. Quando chegamos a este mundo, algumas sementes nos são dadas, e as perguntas são: O que faremos com essas sementes?",
    href: "arquivosDownload/oJardimDaVida05.pdf",
  },
  {
    id: 16,
    img: "static/images/downloads/leao.png",
    title: "O Leão e a Ovelha",
    body: "Às vezes esquecemos quem somos. por Prem Rawat Ficamos tão envolvidos em nossas causas e definições que não vemos que cada ser humano tem a mesma ambição: ser feliz, estar em paz...",
    href: "arquivosDownload/oLeaoEAOvelha06.pdf",
  },
  {
    id: 17,
    img: "static/images/downloads/paz.png",
    title: "O Som de Estar Contente",
    body: "Todos nós somos seres humanos. E de certa forma nossas vidas são semelhantes. Acordamos de manhã. Temos nossos trabalhos, nossas responsabilidades...",
    href: "arquivosDownload/oSomDeEstarContente07.pdf",
  },
  {
    id: 18,
    img: "static/images/downloads/irmaos.png",
    title: "Os Três Irmãos",
    body: "Era uma vez três irmãos que tinham vivido uma infância abastada. Quando ficaram mais velhos, seus pais morreram e eles perderam todo o dinheiro...",
    href: "arquivosDownload/osTresIrmaos08.pdf",
  },
  {
    id: 19,
    img: "static/images/downloads/formiga.png",
    title: "A História da Formiga",
    body: "Tendemos a analizar tudo. Mas quando sinto sede, não quero uma análise da água. Não quero descrições da água. Só quero saber de conseguir água para saciar minha sede. Essa é a questão, saciar a sede...",
    href: "arquivosDownload/aHistoriaDaFormiga09.pdf",
  },
  {
    id: 20,
    img: "static/images/downloads/caderno.png",
    title: "A Melhor Hora",
    body: "Quando vim para o Ocidente, eu tinha apenas 13 anos. E as pessoas vinham me ver, adultos mais velhos, mais educados, mais inteligentes do que eu. Pelo menos, era assim que eles pareciam...",
    href: "arquivosDownload/aMelhorHora10.pdf",
  },
  {
    id: 21,
    img: "static/images/downloads/jornada.png",
    title: "Ansiando Pela Paz",
    body: "Eu estou aqui para falar sobre algo muito fundamental. Você tem um anseio, um desejo a ser preenchido. E esse desejo não desaparecerá enquanto você viver...",
    href: "arquivosDownload/ansiandoPelaPaz11.pdf",
  },
  {
    id: 22,
    img: "static/images/downloads/pedra.png",
    title: "Quando Você Tem Clareza",
    body: "Você me ouvirá dizer esta palavra muitas, muitas vezes: clareza.O que quero dizer com ela? O que é clareza? Ter clareza é estar claro, saber o valor do hoje...",
    href: "arquivosDownload/quandoVoceTemClareza12.pdf",
  },
  {
    id: 23,
    img: "static/images/downloads/porta.png",
    title: "Sabe Quem Você É?",
    body: "Você sabe quem você é? Você não tem que responder isso para os outros. Não para a sua esposa ou seu marido, e não para seus filhos...",
    href: "arquivosDownload/sabeQuemVoceE13.pdf",
  },
  {
    id: 24,
    img: "static/images/downloads/paz.png",
    title: "Sua Escolha",
    body: "Paz é quando você está inteiro. Paz é quando você está completo, quando você entende. Tudo depende das escolhas que você faz em sua vida...",
    href: "arquivosDownload/suaEscolha14.pdf",
  },
  {
    id: 25,
    img: "static/images/downloads/paz.png",
    title: "Um Mundo de Entendimento",
    body: "A vida é um presente. Eu quero entender isso com a maior clareza possível antes que eu perca a capacidade de entender...",
    href: "arquivosDownload/umMundoDeEntendimento15.pdf",
  },
  {
    id: 26,
    img: "static/images/downloads/pedra.png",
    title: "O Empresário e a Pedra Mágica",
    body: "Era uma vez um empreário que tinha um pequeno negócio. Claro que, sendo um empresário, sua vontade era a de ganhar o máximo de dinheiro possível...",
    href: "arquivosDownload/oEmpresaropEAPedraMagica16.pdf",
  },
  {
    id: 27,
    img: "static/images/downloads/paz.png",
    title: "A Porta Até Você",
    body: "Neste Caminho da Existência, não sabemos quais perguntas precisamos fazer para nos orientar. E, se não sabemos de que forma questionar, como iremos encontrar as respostas?",
    href: "arquivosDownload/aPorta17.pdf",
  },
  {
    id: 28,
    img: "static/images/downloads/paz.png",
    title: "Apreciar a Vida",
    body: "Apreciação começa dentro de você, não em outras pessoas. Apreciar, antes de tudo, o fato de estar vivo. Apreciar por existir dentro de você...",
    href: "arquivosDownload/apreciarAVida18.pdf",
  },
  {
    id: 29,
    img: "static/images/downloads/paz.png",
    title: "A Verdadeira Força Interior",
    body: "Uma pessoa pode ser incrivelmente bem-sucedida, mas ao mesmo tempo incrivelmente triste, porque a verdadeira felicidade se manifesta de dentro...",
    href: "arquivosDownload/aVerdadeiraForca19.pdf",
  },
  {
    id: 30,
    img: "static/images/downloads/jornada.png",
    title: "A Jornada da vida - Força Interior",
    body: "NESTA VIDA você é um viajante solitário. E se você não entender a natureza da viagem, vai se perder, porque a vida é a única jornada que, por natureza, não pode andar em um círculos...",
    href: "arquivosDownload/AJornadaDaVida20.pdf",
  },
  {
    id: 31,
    img: "static/images/downloads/paz.png",
    title: "Um Pouco de Espaço",
    body: "Quando penso sobre o que quero, apenas como ser humano, a lista de quesitos não é assim tão grande. O que quero, e o que todos querem...",
    href: "arquivosDownload/umPoucoDeEspaco21.pdf",
  },
  {
    id: 32,
    img: "static/images/downloads/paz.png",
    title: "O Oceano da Esperança",
    body: "Eu tenho algo muito especial para dizer: existe esperança todos os dias. Não é uma questão de anos, não é uma questão de meses, também não é uma questão de semanas...",
    href: "arquivosDownload/oceanoDaEsperanca22.pdf",
  },
  {
    id: 33,
    img: "static/images/downloads/caderno.png",
    title: "Caderno de Anotações",
    body: "“A paz precisa estar na vida de todos. Não é o mundo que precisa de paz, são as pessoas. Quando as pessoas no mundo estiverem em paz, O mundo estará em paz.”",
    href: "arquivosDownload/v3/caderno de anotacoes.pdf",
  },
];

export default Links;
